// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Exam_MVC_App.Models;

[Table("Branch")]
public partial class Branch
{
    public Branch()
    {

        Users = new HashSet<User>();
    }
    [Key]
    public byte Id { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string? Name { get; set; }
    [ForeignKey("Manager")]
    public int? Mng_Id { get; set; }
    public virtual User Manager { get; set; }

    [InverseProperty("Branch")]
    public virtual ICollection<User> Users { get; set; }
}