// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Exam_MVC_App.Models;

[Table("Course")]
public partial class Course
{
    [Key]
    public int Id { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string? Name { get; set; }

    public byte? Hours { get; set; }

    [InverseProperty("Course")]
    public virtual ICollection<Exam> Exams { get; set; } = new List<Exam>();

    [InverseProperty("Course")]
    public virtual ICollection<Instructor_Detial> Instructor_Detials { get; set; } = new List<Instructor_Detial>();

    [InverseProperty("Course")]
    public virtual ICollection<Question> Questions { get; set; } = new List<Question>();

    [InverseProperty("Course")]
    public virtual ICollection<Stundent_Course> Stundent_Courses { get; set; } = new List<Stundent_Course>();
}