// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Exam_MVC_App.Models;

[Table("Exam_Question")]
public partial class Exam_Question
{
    [Key]
    public int Id { get; set; }

    public int Question_Id { get; set; }

    public int Exam_Id { get; set; }

    [ForeignKey("Exam_Id")]
    [InverseProperty("Exam_Questions")]
    public virtual Exam Exam { get; set; } = null!;

    [ForeignKey("Question_Id")]
    [InverseProperty("Exam_Questions")]
    public virtual Question Question { get; set; } = null!;

    [InverseProperty("Exam_Question")]
    public virtual ICollection<Student_Answer> Student_Answers { get; set; } = new List<Student_Answer>();
}