// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Exam_MVC_App.Models;

[Table("Exam")]
public partial class Exam
{
    [Key]
    public int Id { get; set; }

    [Unicode(false)]
    public string Name { get; set; } = null!;

    public int Duration { get; set; }

    public DateOnly Date { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string? Status { get; set; }

    public byte? Hard_Count { get; set; }

    public byte? Normal_Count { get; set; }

    public byte? Easy_Count { get; set; }

    public byte Total_Marks { get; set; }

    public int Course_Id { get; set; }

    [ForeignKey("Course_Id")]
    [InverseProperty("Exams")]
    public virtual Course Course { get; set; } = null!;

    [InverseProperty("Exam")]
    public virtual ICollection<Exam_Question> Exam_Questions { get; set; } = new List<Exam_Question>();
}