// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Exam_MVC_App.Models;

[Table("Question")]
public partial class Question
{
    [Key]
    public int Id { get; set; }

    [Unicode(false)]
    public string Name { get; set; } = null!;

    [StringLength(30)]
    [Unicode(false)]
    public string Type { get; set; } = null!;

    [StringLength(10)]
    [Unicode(false)]
    public string Type_Difficult { get; set; } = null!;

    [StringLength(10)]
    [Unicode(false)]
    public string Type_Multi_Single { get; set; } = null!;

    public byte Mark { get; set; }

    public int Course_Id { get; set; }

    [ForeignKey("Course_Id")]
    [InverseProperty("Questions")]
    public virtual Course Course { get; set; } = null!;

    [InverseProperty("Question")]
    public virtual ICollection<Exam_Question> Exam_Questions { get; set; } = new List<Exam_Question>();

    [InverseProperty("Question")]
    public virtual ICollection<Question_Choice> Question_Choices { get; set; } = new List<Question_Choice>();

    [InverseProperty("Question")]
    public virtual ICollection<Question_Right_Answer> Question_Right_Answers { get; set; } = new List<Question_Right_Answer>();
}