// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace Exam_MVC_App.Models
{
    public partial class sp_correct_examResult
    {
        public int studentid { get; set; }
        public int? examid { get; set; }
        [Column("earnedmarks", TypeName = "decimal(38,2)")]
        public decimal? earnedmarks { get; set; }
        public byte? totalmarks { get; set; }
    }
}
