// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace Exam_MVC_App.Models
{
    public partial class sp_GetExamQuestionsWithChoicesResult
    {
        [StringLength(2147483647)]
        public string ExamName { get; set; } = default!;
        [StringLength(2147483647)]
        public string QuestionText { get; set; } = default!;
        [StringLength(2147483647)]
        public string? ChoiceText { get; set; }
    }
}
