// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace Exam_MVC_App.Models
{
    public partial class sp_show_examResult
    {
        public int Id { get; set; }
        [StringLength(2147483647)]
        public string Name { get; set; } = default!;
        public int Duration { get; set; }
        public DateOnly Date { get; set; }
        [StringLength(20)]
        public string? Status { get; set; }
        public byte? Hard_Count { get; set; }
        public byte? Normal_Count { get; set; }
        public byte? Easy_Count { get; set; }
        public byte Total_Marks { get; set; }
        public int Course_Id { get; set; }
        [StringLength(50)]
        public string? Course_Name { get; set; }
    }
}
