// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace Exam_MVC_App.Models
{
    public partial class sp_show_student_answerResult
    {
        [StringLength(41)]
        public string StudentName { get; set; } = default!;
        [StringLength(2147483647)]
        public string Exam { get; set; } = default!;
        [StringLength(2147483647)]
        public string Question { get; set; } = default!;
        public int id { get; set; }
        [StringLength(2147483647)]
        public string Answer { get; set; } = default!;
        public int User_Id { get; set; }
        public int Exam_Question_Id { get; set; }
    }
}
