// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace Exam_MVC_App.Models
{
    public partial class sp_showUserResult
    {
        public int Id { get; set; }
        [StringLength(20)]
        public string Fname { get; set; } = default!;
        [StringLength(20)]
        public string Lname { get; set; } = default!;
        [StringLength(10)]
        public string Role { get; set; } = default!;
        [StringLength(15)]
        public string? Phone { get; set; }
        [StringLength(50)]
        public string Email { get; set; } = default!;
        [StringLength(50)]
        public string Password { get; set; } = default!;
        [StringLength(50)]
        public string? Gender { get; set; }
        public DateOnly? DateOfBirth { get; set; }
        [StringLength(20)]
        public string Status { get; set; } = default!;
        [Column("Salary", TypeName = "money")]
        public decimal? Salary { get; set; }
        public byte? Branch_Id { get; set; }
    }
}
