// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace Exam_MVC_App.Models
{
    public partial class sp_show_choicesResult
    {
        [StringLength(2147483647)]
        public string Question { get; set; } = default!;
        [StringLength(2147483647)]
        public string Choice { get; set; } = default!;
        public int Choice_Id { get; set; }
    }
}
