// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Exam_MVC_App.Models;

[Table("Student_Answer")]
public partial class Student_Answer
{
    [Key]
    public int id { get; set; }

    [Unicode(false)]
    public string Answer { get; set; } = null!;

    public int User_Id { get; set; }

    public int Exam_Question_Id { get; set; }

    [ForeignKey("Exam_Question_Id")]
    [InverseProperty("Student_Answers")]
    public virtual Exam_Question Exam_Question { get; set; } = null!;

    [ForeignKey("User_Id")]
    [InverseProperty("Student_Answers")]
    public virtual User User { get; set; } = null!;
}