// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Exam_MVC_App.Models;

public partial class Student_Detial
{
    [Key]
    public int Id { get; set; }

    public int User_Id { get; set; }

    public byte Track_Id { get; set; }

    [ForeignKey("Track_Id")]
    [InverseProperty("Student_Detials")]
    public virtual Track Track { get; set; } = null!;

    [ForeignKey("User_Id")]
    [InverseProperty("Student_Detials")]
    public virtual User User { get; set; } = null!;
}