// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Exam_MVC_App.Models;

[Table("User")]
public partial class User
{
    [Key]
    public int Id { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string Fname { get; set; } = null!;

    [StringLength(20)]
    [Unicode(false)]
    public string Lname { get; set; } = null!;

    [StringLength(10)]
    [Unicode(false)]
    public string Role { get; set; } = null!;

    [StringLength(15)]
    [Unicode(false)]
    public string? Phone { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Email { get; set; } = null!;

    [StringLength(50)]
    [Unicode(false)]
    public string Password { get; set; } = null!;

    [StringLength(50)]
    [Unicode(false)]
    public string? Gender { get; set; }

    public DateOnly? DateOfBirth { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string Status { get; set; } = null!;

    [Column(TypeName = "money")]
    public decimal? Salary { get; set; }

    public byte? Branch_Id { get; set; }

    [ForeignKey("Branch_Id")]
    [InverseProperty("Users")]
    public virtual Branch? Branch { get; set; }

    [InverseProperty("User")]
    public virtual ICollection<Instructor_Detial> Instructor_Detials { get; set; } = new List<Instructor_Detial>();

    [InverseProperty("User")]
    public virtual ICollection<Student_Answer> Student_Answers { get; set; } = new List<Student_Answer>();

    [InverseProperty("User")]
    public virtual ICollection<Student_Detial> Student_Detials { get; set; } = new List<Student_Detial>();

    [InverseProperty("User")]
    public virtual ICollection<Stundent_Course> Stundent_Courses { get; set; } = new List<Stundent_Course>();

    [InverseProperty("Mng")]
    public virtual ICollection<Track> Tracks { get; set; } = new List<Track>();
}