// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using System;
using System.Data;
using System.Linq;
using Exam_MVC_App.Models;

namespace Exam_MVC_App.Data
{
    public partial class AppDBContext
    {

        [DbFunction("studentTotalMark", "dbo")]
        public static decimal? studentTotalMark(int? id)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        protected void OnModelCreatingGeneratedFunctions(ModelBuilder modelBuilder)
        {
        }
    }
}
